export {default as NavMenuTextIcon} from './NavMenuTextIcon'
export {default as PageIcon} from './PageIcon'
export {default as ContentIcon} from './ContentIcon'
export {default as VirtualsiteIcon} from './VirtualsiteIcon'
export {getIcon} from './iconRegistry'